<!DOCTYPE html>
<html><head><title>PSDirectException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 instantiations of PSDirectException</div><div class="rA">System.Management.Automation (3)</div><div class="rG" id="System.Management.Automation"><div class="rF"><div class="rN">engine\remoting\common\RemoteSessionHyperVSocket.cs (3)</div>
<a href="../engine/remoting/common/RemoteSessionHyperVSocket.cs.html#431"><b>431</b>throw new <i>PSDirectException</i>(</a>
<a href="../engine/remoting/common/RemoteSessionHyperVSocket.cs.html#508"><b>508</b>throw new <i>PSDirectException</i>(</a>
<a href="../engine/remoting/common/RemoteSessionHyperVSocket.cs.html#582"><b>582</b>throw new <i>PSDirectException</i>(</a>
</div>
</div>
<div class="rH">6 references to PSDirectException</div><div class="rA">System.Management.Automation (6)</div><div class="rG" id="System.Management.Automation"><div class="rF"><div class="rN">engine\remoting\commands\InvokeCommandCommand.cs (2)</div>
<a href="../engine/remoting/commands/InvokeCommandCommand.cs.html#1993"><b>1993</b><i>PSDirectException</i> ex = errorRecord.Exception.InnerException as <i>PSDirectException</i>;</a>
</div>
<div class="rF"><div class="rN">engine\remoting\commands\newrunspacecommand.cs (2)</div>
<a href="../engine/remoting/commands/newrunspacecommand.cs.html#555"><b>555</b><i>PSDirectException</i> ex = errorRecord.Exception.InnerException as <i>PSDirectException</i>;</a>
</div>
<div class="rF"><div class="rN">engine\remoting\commands\PushRunspaceCommand.cs (2)</div>
<a href="../engine/remoting/commands/PushRunspaceCommand.cs.html#1053"><b>1053</b>if ((e.InnerException != null) &amp;&amp; (e.InnerException is <i>PSDirectException</i>))</a>
<a href="../engine/remoting/commands/PushRunspaceCommand.cs.html#1229"><b>1229</b>if ((e.InnerException != null) &amp;&amp; (e.InnerException is <i>PSDirectException</i>))</a>
</div>
</div>
</body></html>