<!DOCTYPE html>
<html><head><title>_errorRecord</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">5 writes to _errorRecord</div><div class="rA">System.Management.Automation (5)</div><div class="rG" id="System.Management.Automation"><div class="rF"><div class="rN">utils\RuntimeException.cs (5)</div>
<a href="../utils/RuntimeException.cs.html#105"><b>105</b><i>_errorRecord</i> = errorRecord;</a>
<a href="../utils/RuntimeException.cs.html#125"><b>125</b><i>_errorRecord</i> = new ErrorRecord(</a>
<a href="../utils/RuntimeException.cs.html#156"><b>156</b><i>_errorRecord</i> = new ErrorRecord(</a>
<a href="../utils/RuntimeException.cs.html#184"><b>184</b><i>_errorRecord</i> = null;</a>
<a href="../utils/RuntimeException.cs.html#202"><b>202</b><i>_errorRecord</i> = null;</a>
</div>
</div>
<div class="rH">7 references to _errorRecord</div><div class="rA">System.Management.Automation (7)</div><div class="rG" id="System.Management.Automation"><div class="rF"><div class="rN">utils\RuntimeException.cs (7)</div>
<a href="../utils/RuntimeException.cs.html#130"><b>130</b><i>_errorRecord</i>.SetInvocationInfo(new InvocationInfo(invocationInfo.MyCommand, errorPosition));</a>
<a href="../utils/RuntimeException.cs.html#154"><b>154</b>if (<i>_errorRecord</i> == null)</a>
<a href="../utils/RuntimeException.cs.html#163"><b>163</b>return <i>_errorRecord</i>;</a>
<a href="../utils/RuntimeException.cs.html#217"><b>217</b>if (<i>_errorRecord</i> != null)</a>
<a href="../utils/RuntimeException.cs.html#218"><b>218</b><i>_errorRecord</i>.SetTargetObject(targetObject);</a>
<a href="../utils/RuntimeException.cs.html#274"><b>274</b>if (<i>_errorRecord</i> != null)</a>
<a href="../utils/RuntimeException.cs.html#276"><b>276</b>RuntimeException exception = <i>_errorRecord</i>.Exception as RuntimeException;</a>
</div>
</div>
</body></html>